version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: 22000
    container_name: laravel-app
    ports:
      - 8111:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/source
    networks:
      backend:
        aliases:
          - app
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456a
      - MYSQL_DATABASE=source
      - MYSQL_USER=source
      - MYSQL_PASSWORD=123456a
    networks:
      backend:
        aliases:
          - mysql-db

networks:
  backend:
    name: backend-network
